"""Added more columns to items table

Revision ID: b2f3c43e55d3
Revises: 
Create Date: 2024-09-09 21:12:52.348225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f3c43e55d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values to avoid NOT NULL constraint issues
    op.add_column('items', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('items', sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()'), nullable=True))

    # Update existing rows to set default values for the new columns
    op.execute("UPDATE items SET price = 0 WHERE price IS NULL")
    op.execute("UPDATE items SET is_available = TRUE WHERE is_available IS NULL")
    op.execute("UPDATE items SET stock_quantity = 0 WHERE stock_quantity IS NULL")

    # Alter columns to set NOT NULL constraints if required
    op.alter_column('items', 'price', existing_type=sa.Float(), nullable=False)
    op.alter_column('items', 'is_available', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('items', 'stock_quantity', existing_type=sa.Integer(), nullable=False)

    # Adjust indexes
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_name', table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index('ix_items_name', 'items', ['name'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)

    # Revert column constraints
    op.alter_column('items', 'price', existing_type=sa.Float(), nullable=True)
    op.alter_column('items', 'is_available', existing_type=sa.Boolean(), nullable=True)
    op.alter_column('items', 'stock_quantity', existing_type=sa.Integer(), nullable=True)
    
    # Drop columns
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'stock_quantity')
    op.drop_column('items', 'is_available')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
